name: Publish package
on:
  push:
    branches: main
    paths:
      - "packages/components/package.json"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: install
        run: npm install
      - name: build
        run: yarn workspace @cabindao/topo build
      - uses: JS-DevTools/npm-publish@v1
        working-directory: packages/components
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          check-version: false
