name: Lint & Build
on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: install
        run: npm install
      - name: yarn
        run: yarn
      - name: Lint
        run: yarn lint
      - name: build
        run: yarn build:npm
