name: Lint & Build
on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.6
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: install
        run: npm install
      - name: yarn
        run: yarn
      - name: Lint
        run: npm run lint
        working-directory: packages/components
      - name: build theme
        run: yarn workspace @cabindao/topo-theme build:npm
      - name: build
        run: yarn workspace @cabindao/topo build:npm
